// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Moviesite.Data;

namespace Moviesite.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Moviesite.Entities.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime>("DateBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Australia",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 682, DateTimeKind.Local).AddTicks(3463),
                            Gender = "Male",
                            Name = "Chris Hemsworth"
                        },
                        new
                        {
                            Id = 2,
                            Country = "USA",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 686, DateTimeKind.Local).AddTicks(6720),
                            Gender = "Male",
                            Name = "Robert Downey Jr."
                        },
                        new
                        {
                            Id = 3,
                            Country = "USA",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 686, DateTimeKind.Local).AddTicks(6794),
                            Gender = "Male",
                            Name = "Chris Evans"
                        },
                        new
                        {
                            Id = 4,
                            Country = "USA",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 686, DateTimeKind.Local).AddTicks(6802),
                            Gender = "Female",
                            Name = "Scarlett Johansson"
                        },
                        new
                        {
                            Id = 5,
                            Country = "USA",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 686, DateTimeKind.Local).AddTicks(6807),
                            Gender = "Male",
                            Name = "Mark Ruffalo"
                        },
                        new
                        {
                            Id = 6,
                            Country = "USA",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 686, DateTimeKind.Local).AddTicks(6811),
                            Gender = "Male",
                            Name = "Jeremy Lee Renner"
                        },
                        new
                        {
                            Id = 7,
                            Country = "England",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 686, DateTimeKind.Local).AddTicks(6817),
                            Gender = "Male",
                            Name = "Tom Hiddleston"
                        },
                        new
                        {
                            Id = 8,
                            Country = "USA",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 686, DateTimeKind.Local).AddTicks(6821),
                            Gender = "Male",
                            Name = "Robert Clark Gregg"
                        },
                        new
                        {
                            Id = 9,
                            Country = "Canada",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 686, DateTimeKind.Local).AddTicks(6825),
                            Gender = "Female",
                            Name = "Cobie Smulders"
                        },
                        new
                        {
                            Id = 10,
                            Country = "Sweden",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 686, DateTimeKind.Local).AddTicks(6829),
                            Gender = "Male",
                            Name = "Stellan John Skarsgard"
                        },
                        new
                        {
                            Id = 11,
                            Country = "USA",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 686, DateTimeKind.Local).AddTicks(6832),
                            Gender = "Male",
                            Name = "Samuel L. Jackson"
                        },
                        new
                        {
                            Id = 12,
                            Country = "USA",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 686, DateTimeKind.Local).AddTicks(6836),
                            Gender = "Female",
                            Name = "Karen Gillan"
                        },
                        new
                        {
                            Id = 13,
                            Country = "USA",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 686, DateTimeKind.Local).AddTicks(6840),
                            Gender = "Female",
                            Name = "Brie Larson"
                        },
                        new
                        {
                            Id = 14,
                            Country = "USA",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 686, DateTimeKind.Local).AddTicks(6843),
                            Gender = "Male",
                            Name = "Jon Favreau"
                        },
                        new
                        {
                            Id = 15,
                            Country = "USA",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 686, DateTimeKind.Local).AddTicks(6847),
                            Gender = "Male",
                            Name = "Bradley Cooper"
                        },
                        new
                        {
                            Id = 16,
                            Country = "USA",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 686, DateTimeKind.Local).AddTicks(6851),
                            Gender = "Male",
                            Name = "Josh Brolin"
                        },
                        new
                        {
                            Id = 17,
                            Country = "USA",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 686, DateTimeKind.Local).AddTicks(6854),
                            Gender = "Male",
                            Name = "Clark Gregg"
                        },
                        new
                        {
                            Id = 18,
                            Country = "USA",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 686, DateTimeKind.Local).AddTicks(6858),
                            Gender = "Male",
                            Name = "Paul Bettany"
                        },
                        new
                        {
                            Id = 19,
                            Country = "USA",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 686, DateTimeKind.Local).AddTicks(6862),
                            Gender = "Female",
                            Name = "Gwyneth Paltrow"
                        },
                        new
                        {
                            Id = 20,
                            Country = "USA",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 686, DateTimeKind.Local).AddTicks(6865),
                            Gender = "Male",
                            Name = "Terrence Howard"
                        },
                        new
                        {
                            Id = 21,
                            Country = "USA",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 686, DateTimeKind.Local).AddTicks(6869),
                            Gender = "Male",
                            Name = "Jeff Bridges"
                        },
                        new
                        {
                            Id = 22,
                            Country = "USA",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 686, DateTimeKind.Local).AddTicks(6874),
                            Gender = "Male",
                            Name = "Don Cheadle"
                        },
                        new
                        {
                            Id = 23,
                            Country = "USA",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 686, DateTimeKind.Local).AddTicks(6879),
                            Gender = "Male",
                            Name = "Edward Norton"
                        },
                        new
                        {
                            Id = 24,
                            Country = "USA",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 686, DateTimeKind.Local).AddTicks(6882),
                            Gender = "Male",
                            Name = "Tim Roth"
                        },
                        new
                        {
                            Id = 25,
                            Country = "USA",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 686, DateTimeKind.Local).AddTicks(6886),
                            Gender = "Male",
                            Name = "Liv Tyler"
                        },
                        new
                        {
                            Id = 26,
                            Country = "USA",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 686, DateTimeKind.Local).AddTicks(6931),
                            Gender = "Male",
                            Name = "Mickey Rourke"
                        },
                        new
                        {
                            Id = 27,
                            Country = "USA",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 686, DateTimeKind.Local).AddTicks(6934),
                            Gender = "Female",
                            Name = "Natalie Portman"
                        },
                        new
                        {
                            Id = 28,
                            Country = "USA",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 686, DateTimeKind.Local).AddTicks(6938),
                            Gender = "Female",
                            Name = "Rene Russo"
                        },
                        new
                        {
                            Id = 29,
                            Country = "USA",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 686, DateTimeKind.Local).AddTicks(6942),
                            Gender = "Male",
                            Name = "Idris Elba"
                        },
                        new
                        {
                            Id = 30,
                            Country = "Japan",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 686, DateTimeKind.Local).AddTicks(6946),
                            Gender = "Male",
                            Name = "Tadanobu Asano"
                        },
                        new
                        {
                            Id = 31,
                            Country = "USA",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 686, DateTimeKind.Local).AddTicks(6950),
                            Gender = "Female",
                            Name = "Kat Dennings"
                        },
                        new
                        {
                            Id = 32,
                            Country = "USA",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 686, DateTimeKind.Local).AddTicks(6953),
                            Gender = "Male",
                            Name = "Anthony Hopkins"
                        },
                        new
                        {
                            Id = 33,
                            Country = "USA",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 686, DateTimeKind.Local).AddTicks(6957),
                            Gender = "Female",
                            Name = "Jaimie Alexander"
                        },
                        new
                        {
                            Id = 34,
                            Country = "Ireland",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 686, DateTimeKind.Local).AddTicks(6961),
                            Gender = "Male",
                            Name = "Ray Stevenson"
                        },
                        new
                        {
                            Id = 35,
                            Country = "Romania",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 686, DateTimeKind.Local).AddTicks(6964),
                            Gender = "Male",
                            Name = "Sebastian Stan"
                        },
                        new
                        {
                            Id = 36,
                            Country = "England",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 686, DateTimeKind.Local).AddTicks(6968),
                            Gender = "Female",
                            Name = "Hayley Atwell"
                        },
                        new
                        {
                            Id = 37,
                            Country = "USA",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 686, DateTimeKind.Local).AddTicks(6972),
                            Gender = "Male",
                            Name = "Tommy Lee Jones"
                        },
                        new
                        {
                            Id = 38,
                            Country = "Canada",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 686, DateTimeKind.Local).AddTicks(6975),
                            Gender = "Female",
                            Name = "Evangeline Lilly"
                        },
                        new
                        {
                            Id = 39,
                            Country = "USA",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 686, DateTimeKind.Local).AddTicks(6979),
                            Gender = "Female",
                            Name = "Chris Pratt"
                        },
                        new
                        {
                            Id = 40,
                            Country = "USA",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 686, DateTimeKind.Local).AddTicks(6982),
                            Gender = "Female",
                            Name = "Zoe Saldana"
                        },
                        new
                        {
                            Id = 41,
                            Country = "USA",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 686, DateTimeKind.Local).AddTicks(6986),
                            Gender = "Male",
                            Name = "Vin Diesel"
                        },
                        new
                        {
                            Id = 42,
                            Country = "USA",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 686, DateTimeKind.Local).AddTicks(6990),
                            Gender = "Male",
                            Name = "Dave Bautista"
                        },
                        new
                        {
                            Id = 43,
                            Country = "USA",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 686, DateTimeKind.Local).AddTicks(6993),
                            Gender = "Male",
                            Name = "Kurt Russell"
                        },
                        new
                        {
                            Id = 44,
                            Country = "England",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 686, DateTimeKind.Local).AddTicks(6997),
                            Gender = "Male",
                            Name = "Tom Holland"
                        },
                        new
                        {
                            Id = 45,
                            Country = "USA",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 686, DateTimeKind.Local).AddTicks(7001),
                            Gender = "Male",
                            Name = "Anthony Mackie"
                        },
                        new
                        {
                            Id = 46,
                            Country = "USA",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 686, DateTimeKind.Local).AddTicks(7005),
                            Gender = "Female",
                            Name = "Elizabeth Olsen"
                        },
                        new
                        {
                            Id = 47,
                            Country = "USA",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 686, DateTimeKind.Local).AddTicks(7008),
                            Gender = "Male",
                            Name = "Paul Rudd"
                        },
                        new
                        {
                            Id = 48,
                            Country = "USA",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 686, DateTimeKind.Local).AddTicks(7012),
                            Gender = "Male",
                            Name = "Benedict Cumberbatch"
                        },
                        new
                        {
                            Id = 49,
                            Country = "USA",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 686, DateTimeKind.Local).AddTicks(7016),
                            Gender = "Male",
                            Name = "Michael B. Jordan"
                        },
                        new
                        {
                            Id = 50,
                            Country = "USA",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 686, DateTimeKind.Local).AddTicks(7020),
                            Gender = "Male",
                            Name = "Chadwick Boseman"
                        },
                        new
                        {
                            Id = 51,
                            Country = "USA",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 686, DateTimeKind.Local).AddTicks(7023),
                            Gender = "Male",
                            Name = "Jake Gyllenhaal"
                        });
                });

            modelBuilder.Entity("Moviesite.Entities.Director", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime>("DateBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.ToTable("Directors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "USA",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 689, DateTimeKind.Local).AddTicks(7892),
                            Gender = "Male",
                            Name = "Kevin Feige",
                            ShortDescription = ""
                        },
                        new
                        {
                            Id = 2,
                            Country = "USA",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 689, DateTimeKind.Local).AddTicks(9193),
                            Gender = "Male",
                            Name = "Joe Russo",
                            ShortDescription = ""
                        },
                        new
                        {
                            Id = 3,
                            Country = "USA",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 689, DateTimeKind.Local).AddTicks(9257),
                            Gender = "Male",
                            Name = "Anthony Russo",
                            ShortDescription = ""
                        },
                        new
                        {
                            Id = 4,
                            Country = "USA",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 689, DateTimeKind.Local).AddTicks(9263),
                            Gender = "Female",
                            Name = "Anna Boden",
                            ShortDescription = ""
                        },
                        new
                        {
                            Id = 5,
                            Country = "USA",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 689, DateTimeKind.Local).AddTicks(9269),
                            Gender = "Male",
                            Name = "Jon Favreau",
                            ShortDescription = ""
                        },
                        new
                        {
                            Id = 6,
                            Country = "USA",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 689, DateTimeKind.Local).AddTicks(9273),
                            Gender = "Male",
                            Name = "Shane Black",
                            ShortDescription = ""
                        },
                        new
                        {
                            Id = 7,
                            Country = "USA",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 689, DateTimeKind.Local).AddTicks(9277),
                            Gender = "Male",
                            Name = "Louis Leterrier",
                            ShortDescription = ""
                        },
                        new
                        {
                            Id = 8,
                            Country = "USA",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 689, DateTimeKind.Local).AddTicks(9282),
                            Gender = "Male",
                            Name = "Taika Waititi",
                            ShortDescription = ""
                        },
                        new
                        {
                            Id = 9,
                            Country = "USA",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 689, DateTimeKind.Local).AddTicks(9286),
                            Gender = "Male",
                            Name = "Alan Taylor",
                            ShortDescription = ""
                        },
                        new
                        {
                            Id = 10,
                            Country = "USA",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 689, DateTimeKind.Local).AddTicks(9290),
                            Gender = "Male",
                            Name = "Joss Whedon",
                            ShortDescription = ""
                        },
                        new
                        {
                            Id = 11,
                            Country = "USA",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 689, DateTimeKind.Local).AddTicks(9295),
                            Gender = "Male",
                            Name = "Joe Johnston",
                            ShortDescription = ""
                        },
                        new
                        {
                            Id = 12,
                            Country = "USA",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 689, DateTimeKind.Local).AddTicks(9299),
                            Gender = "Male",
                            Name = "James Gunn",
                            ShortDescription = ""
                        },
                        new
                        {
                            Id = 13,
                            Country = "USA",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 689, DateTimeKind.Local).AddTicks(9504),
                            Gender = "Male",
                            Name = "Peyton Reed",
                            ShortDescription = ""
                        },
                        new
                        {
                            Id = 14,
                            Country = "USA",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 689, DateTimeKind.Local).AddTicks(9509),
                            Gender = "Male",
                            Name = "Jon Watts",
                            ShortDescription = ""
                        },
                        new
                        {
                            Id = 15,
                            Country = "USA",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 689, DateTimeKind.Local).AddTicks(9514),
                            Gender = "Male",
                            Name = "Scott Derrickson",
                            ShortDescription = ""
                        },
                        new
                        {
                            Id = 16,
                            Country = "USA",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 689, DateTimeKind.Local).AddTicks(9519),
                            Gender = "Male",
                            Name = "Ryan Coogler",
                            ShortDescription = ""
                        },
                        new
                        {
                            Id = 17,
                            Country = "Ireland",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 689, DateTimeKind.Local).AddTicks(9524),
                            Gender = "Male",
                            Name = "Kenneth Branagh",
                            ShortDescription = ""
                        });
                });

            modelBuilder.Entity("Moviesite.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Fiction"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Crime"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = 8,
                            Name = "General"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Sci-Fi"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Uncategorised"
                        });
                });

            modelBuilder.Entity("Moviesite.Entities.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActorNames")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<int>("DirectorID")
                        .HasColumnType("int");

                    b.Property<string>("DirectorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormatType")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("GenreID")
                        .HasColumnType("int");

                    b.Property<string>("GenreName")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("PhotoURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("ProducerID")
                        .HasColumnType("int");

                    b.Property<string>("ProducerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Shipping")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("SoldItems")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(350)")
                        .HasMaxLength(350);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DirectorID");

                    b.HasIndex("GenreID");

                    b.HasIndex("ProducerID");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActorNames = "Chris Evans, Samuel L. Jackson, Hayley Atwell, Sebastian Bach",
                            Country = "USA",
                            DateAdded = new DateTime(2021, 4, 17, 19, 28, 2, 690, DateTimeKind.Local).AddTicks(2549),
                            Description = "",
                            DirectorID = 11,
                            DirectorName = "Joe Johnston",
                            Duration = "",
                            FormatType = "",
                            GenreID = 11,
                            GenreName = "Sci-Fi",
                            Language = "English",
                            PhotoURL = "CaptainAmerica.jpg",
                            Price = 12.0,
                            ProducerID = 1,
                            ProducerName = "Kevin Feige",
                            Rating = 5.0,
                            ReleaseDate = new DateTime(2019, 1, 20, 21, 30, 15, 0, DateTimeKind.Unspecified),
                            Shipping = "Yes",
                            SoldItems = 33,
                            Title = "Captain America: The First Avenger",
                            UserId = 0
                        },
                        new
                        {
                            Id = 2,
                            ActorNames = "Brie Larson, Samuel L. Jackson, Clark Gregg",
                            Country = "USA",
                            DateAdded = new DateTime(2021, 4, 17, 19, 28, 2, 691, DateTimeKind.Local).AddTicks(4998),
                            Description = "",
                            DirectorID = 4,
                            DirectorName = "Anna Boden",
                            Duration = "",
                            FormatType = "",
                            GenreID = 11,
                            GenreName = "Sci-Fi",
                            Language = "English",
                            PhotoURL = "CaptainMarvel.jpg",
                            Price = 15.0,
                            ProducerID = 1,
                            ProducerName = "Kevin Feige",
                            Rating = 5.0,
                            ReleaseDate = new DateTime(2019, 2, 20, 21, 30, 15, 0, DateTimeKind.Unspecified),
                            Shipping = "Yes",
                            SoldItems = 12,
                            Title = "Captain Marvel",
                            UserId = 0
                        },
                        new
                        {
                            Id = 3,
                            ActorNames = "Robert Downey Jr., Gwyneth Paltrow, Jon Favreau, Samuel L. Jackson, Jeff Bridges, Terrence Howard, Paul Bettany, Clark Gregg",
                            Country = "USA",
                            DateAdded = new DateTime(2021, 4, 17, 19, 28, 2, 691, DateTimeKind.Local).AddTicks(5212),
                            Description = "",
                            DirectorID = 5,
                            DirectorName = "Jon Favreau",
                            Duration = "",
                            FormatType = "",
                            GenreID = 11,
                            GenreName = "Sci-Fi",
                            Language = "English",
                            PhotoURL = "IronMan.jpg",
                            Price = 11.0,
                            ProducerID = 1,
                            ProducerName = "Kevin Feige",
                            Rating = 5.0,
                            ReleaseDate = new DateTime(2019, 3, 20, 21, 30, 15, 0, DateTimeKind.Unspecified),
                            Shipping = "Yes",
                            SoldItems = 32,
                            Title = "Iron Man",
                            UserId = 0
                        },
                        new
                        {
                            Id = 4,
                            ActorNames = "Robert Downey Jr., Gwyneth Paltrow, Jon Favreau, Samuel L. Jackson, Don Cheadle, Paul Bettany, Clark Gregg, Mickey Rourke",
                            Country = "USA",
                            DateAdded = new DateTime(2021, 4, 17, 19, 28, 2, 691, DateTimeKind.Local).AddTicks(5363),
                            Description = "",
                            DirectorID = 5,
                            DirectorName = "Jon Favreau",
                            Duration = "",
                            FormatType = "",
                            GenreID = 11,
                            GenreName = "Sci-Fi",
                            Language = "English",
                            PhotoURL = "IronMan2.jpg",
                            Price = 22.0,
                            ProducerID = 1,
                            ProducerName = "Kevin Feige",
                            Rating = 5.0,
                            ReleaseDate = new DateTime(2019, 4, 20, 21, 30, 15, 0, DateTimeKind.Unspecified),
                            Shipping = "Yes",
                            SoldItems = 50,
                            Title = "Iron Man 2",
                            UserId = 0
                        },
                        new
                        {
                            Id = 5,
                            ActorNames = "Edward Norton, Tim Roth",
                            Country = "USA",
                            DateAdded = new DateTime(2021, 4, 17, 19, 28, 2, 691, DateTimeKind.Local).AddTicks(5370),
                            Description = "",
                            DirectorID = 7,
                            DirectorName = "Louis Leterrier",
                            Duration = "",
                            FormatType = "",
                            GenreID = 11,
                            GenreName = "Sci-Fi",
                            Language = "English",
                            PhotoURL = "TheIncredibleHulk.jpg",
                            Price = 16.0,
                            ProducerID = 1,
                            ProducerName = "Kevin Feige",
                            Rating = 5.0,
                            ReleaseDate = new DateTime(2019, 5, 20, 21, 30, 15, 0, DateTimeKind.Unspecified),
                            Shipping = "Yes",
                            SoldItems = 13,
                            Title = "The Incredible Hulk",
                            UserId = 0
                        },
                        new
                        {
                            Id = 6,
                            ActorNames = "Chris Hemsworth, Natalie Portman, Jaimie Alexander, Idris Elba, Anthony Hopkins, Kat Dennings, Rene Russo, Ray Stevenson, Stellan Skarsgard, Tadanobu Asano, Clark Gregg , Samuel L. Jackson, Jeremy Lee Renner, Tom Hiddleston",
                            Country = "USA",
                            DateAdded = new DateTime(2021, 4, 17, 19, 28, 2, 691, DateTimeKind.Local).AddTicks(5376),
                            Description = "",
                            DirectorID = 17,
                            DirectorName = "Kenneth Branagh",
                            Duration = "",
                            FormatType = "",
                            GenreID = 11,
                            GenreName = "Sci-Fi",
                            Language = "English",
                            PhotoURL = "Thor.jpg",
                            Price = 15.0,
                            ProducerID = 1,
                            ProducerName = "Kevin Feige",
                            Rating = 5.0,
                            ReleaseDate = new DateTime(2019, 6, 20, 21, 30, 15, 0, DateTimeKind.Unspecified),
                            Shipping = "Yes",
                            SoldItems = 12,
                            Title = "Thor",
                            UserId = 0
                        },
                        new
                        {
                            Id = 7,
                            ActorNames = "Chris Hemsworth, Mark Ruffalo, Robert Downey Jr., Jeremy Lee Renner, Tom Hiddleston, Chris Evans, Elizabeth Olsen, Paul Bettany, Scarlet Johansson, Samuel L. Jackson",
                            Country = "USA",
                            DateAdded = new DateTime(2021, 4, 17, 19, 28, 2, 691, DateTimeKind.Local).AddTicks(5382),
                            Description = "",
                            DirectorID = 2,
                            DirectorName = "Joe Russo",
                            Duration = "",
                            FormatType = "",
                            GenreID = 11,
                            GenreName = "Sci-Fi",
                            Language = "English",
                            PhotoURL = "Avengers.jpg",
                            Price = 15.0,
                            ProducerID = 1,
                            ProducerName = "Kevin Feige",
                            Rating = 5.0,
                            ReleaseDate = new DateTime(2019, 7, 20, 21, 30, 15, 0, DateTimeKind.Unspecified),
                            Shipping = "Yes",
                            SoldItems = 33,
                            Title = "The Avengers",
                            UserId = 0
                        },
                        new
                        {
                            Id = 8,
                            ActorNames = "Robert Downey Jr., Gwyneth Paltrow, Jon Favreau, Samuel L. Jackson, Don Cheadle, Paul Bettany, Clark Gregg",
                            Country = "USA",
                            DateAdded = new DateTime(2021, 4, 17, 19, 28, 2, 691, DateTimeKind.Local).AddTicks(5388),
                            Description = "",
                            DirectorID = 6,
                            DirectorName = "Shane Black",
                            Duration = "",
                            FormatType = "",
                            GenreID = 11,
                            GenreName = "Sci-Fi",
                            Language = "English",
                            PhotoURL = "IronMan3.jpg",
                            Price = 16.0,
                            ProducerID = 1,
                            ProducerName = "Kevin Feige",
                            Rating = 5.0,
                            ReleaseDate = new DateTime(2019, 8, 20, 21, 30, 15, 0, DateTimeKind.Unspecified),
                            Shipping = "Yes",
                            SoldItems = 34,
                            Title = "Iron Man 3",
                            UserId = 0
                        },
                        new
                        {
                            Id = 9,
                            ActorNames = "Chris Hemsworth, Natalie Portman, Jaimie Alexander, Idris Elba, Anthony Hopkins, Kat Dennings, Rene Russo, Ray Stevenson, Stellan Skarsgard, Tadanobu Asano, Tom Hiddleston",
                            Country = "USA",
                            DateAdded = new DateTime(2021, 4, 17, 19, 28, 2, 691, DateTimeKind.Local).AddTicks(5393),
                            Description = "",
                            DirectorID = 9,
                            DirectorName = "Alan Taylor",
                            Duration = "",
                            FormatType = "",
                            GenreID = 11,
                            GenreName = "Sci-Fi",
                            Language = "English",
                            PhotoURL = "ThorTheDarkWorld.jpg",
                            Price = 16.0,
                            ProducerID = 1,
                            ProducerName = "Kevin Feige",
                            Rating = 5.0,
                            ReleaseDate = new DateTime(2018, 1, 20, 21, 30, 15, 0, DateTimeKind.Unspecified),
                            Shipping = "Yes",
                            SoldItems = 50,
                            Title = "Thor: The Dark World",
                            UserId = 0
                        },
                        new
                        {
                            Id = 10,
                            ActorNames = "Chris Evans, Samuel L. Jackson, Hayley Atwell, Sebastian Bach, Anthony Mackie",
                            Country = "USA",
                            DateAdded = new DateTime(2021, 4, 17, 19, 28, 2, 691, DateTimeKind.Local).AddTicks(5398),
                            Description = "",
                            DirectorID = 3,
                            DirectorName = "Anthony Russo",
                            Duration = "",
                            FormatType = "",
                            GenreID = 11,
                            GenreName = "Sci-Fi",
                            Language = "English",
                            PhotoURL = "CaptainAmericaWinterSoldier.jpg",
                            Price = 16.0,
                            ProducerID = 1,
                            ProducerName = "Kevin Feige",
                            Rating = 5.0,
                            ReleaseDate = new DateTime(2019, 3, 20, 21, 30, 15, 0, DateTimeKind.Unspecified),
                            Shipping = "Yes",
                            SoldItems = 50,
                            Title = "Captain America: Winter Soldier",
                            UserId = 0
                        },
                        new
                        {
                            Id = 11,
                            ActorNames = "Chris Pratt, Zoe Saldana, Vin Diesel, Bradley Cooper, Karen Gillan, Dave Bautista",
                            Country = "USA",
                            DateAdded = new DateTime(2021, 4, 17, 19, 28, 2, 691, DateTimeKind.Local).AddTicks(5404),
                            Description = "",
                            DirectorID = 12,
                            DirectorName = "James Gunn",
                            Duration = "",
                            FormatType = "",
                            GenreID = 11,
                            GenreName = "Sci-Fi",
                            Language = "English",
                            PhotoURL = "GuardiansOfTheGalaxy.jpg",
                            Price = 14.0,
                            ProducerID = 1,
                            ProducerName = "Kevin Feige",
                            Rating = 5.0,
                            ReleaseDate = new DateTime(2018, 4, 20, 21, 30, 15, 0, DateTimeKind.Unspecified),
                            Shipping = "Yes",
                            SoldItems = 34,
                            Title = "Guardians of the Galaxy",
                            UserId = 0
                        },
                        new
                        {
                            Id = 12,
                            ActorNames = "Chris Pratt, Zoe Saldana, Vin Diesel, Bradley Cooper, Karen Gillan, Dave Bautista, Kurt Russel",
                            Country = "USA",
                            DateAdded = new DateTime(2021, 4, 17, 19, 28, 2, 691, DateTimeKind.Local).AddTicks(5409),
                            Description = "",
                            DirectorID = 12,
                            DirectorName = "James Gunn",
                            Duration = "",
                            FormatType = "",
                            GenreID = 11,
                            GenreName = "Sci-Fi",
                            Language = "English",
                            PhotoURL = "GuardiansOfTheGalaxyVol2.jpg",
                            Price = 15.0,
                            ProducerID = 1,
                            ProducerName = "Kevin Feige",
                            Rating = 5.0,
                            ReleaseDate = new DateTime(2018, 3, 20, 21, 30, 15, 0, DateTimeKind.Unspecified),
                            Shipping = "Yes",
                            SoldItems = 14,
                            Title = "Guardians of the Galaxy Vol.2",
                            UserId = 0
                        },
                        new
                        {
                            Id = 13,
                            ActorNames = "Chris Hemsworth, Mark Ruffalo, Robert Downey Jr., Jeremy Lee Renner, Tom Hiddleston, Chris Evans, Elizabeth Olsen, Paul Bettany, Scarlet Johansson, Samuel L. Jackson",
                            Country = "USA",
                            DateAdded = new DateTime(2021, 4, 17, 19, 28, 2, 691, DateTimeKind.Local).AddTicks(5415),
                            Description = "",
                            DirectorID = 10,
                            DirectorName = "Joss Whedon",
                            Duration = "",
                            FormatType = "",
                            GenreID = 11,
                            GenreName = "Sci-Fi",
                            Language = "English",
                            PhotoURL = "AvengersAgeOfUltron.jpg",
                            Price = 18.0,
                            ProducerID = 1,
                            ProducerName = "Kevin Feige",
                            Rating = 5.0,
                            ReleaseDate = new DateTime(2019, 4, 20, 21, 30, 15, 0, DateTimeKind.Unspecified),
                            Shipping = "Yes",
                            SoldItems = 45,
                            Title = "Avengers: Age of Ultron",
                            UserId = 0
                        },
                        new
                        {
                            Id = 14,
                            ActorNames = "Paul Rudd, Michael Douglas",
                            Country = "USA",
                            DateAdded = new DateTime(2021, 4, 17, 19, 28, 2, 691, DateTimeKind.Local).AddTicks(5420),
                            Description = "",
                            DirectorID = 13,
                            DirectorName = "Peyton Reed",
                            Duration = "",
                            FormatType = "",
                            GenreID = 11,
                            GenreName = "Sci-Fi",
                            Language = "English",
                            PhotoURL = "AntMan.jpg",
                            Price = 15.0,
                            ProducerID = 1,
                            ProducerName = "Kevin Feige",
                            Rating = 4.5,
                            ReleaseDate = new DateTime(2019, 7, 20, 21, 30, 15, 0, DateTimeKind.Unspecified),
                            Shipping = "Yes",
                            SoldItems = 30,
                            Title = "Ant-Man",
                            UserId = 0
                        },
                        new
                        {
                            Id = 15,
                            ActorNames = "Chris Evans, Samuel L. Jackson, Robert Downey Jr., Sebastian Bach, Anthony Mackie, Elizabeth Olsen, Scarlet Johansson, Jeremy Lee Renner, Paul Rudd, Tom Holland, Paul Bettany",
                            Country = "USA",
                            DateAdded = new DateTime(2021, 4, 17, 19, 28, 2, 691, DateTimeKind.Local).AddTicks(5480),
                            Description = "",
                            DirectorID = 2,
                            DirectorName = "Joe Russo",
                            Duration = "",
                            FormatType = "",
                            GenreID = 11,
                            GenreName = "Sci-Fi",
                            Language = "English",
                            PhotoURL = "CaptainAmericaCivilWar.jpg",
                            Price = 16.0,
                            ProducerID = 1,
                            ProducerName = "Kevin Feige",
                            Rating = 4.5,
                            ReleaseDate = new DateTime(2019, 2, 20, 21, 30, 15, 0, DateTimeKind.Unspecified),
                            Shipping = "Yes",
                            SoldItems = 44,
                            Title = "Captain America: Civil War",
                            UserId = 0
                        },
                        new
                        {
                            Id = 16,
                            ActorNames = "Tom Holland, Robert Downey Jr., Jon Favreau, Zendaya",
                            Country = "USA",
                            DateAdded = new DateTime(2021, 4, 17, 19, 28, 2, 691, DateTimeKind.Local).AddTicks(5486),
                            Description = "",
                            DirectorID = 14,
                            DirectorName = "Jon Watts",
                            Duration = "",
                            FormatType = "",
                            GenreID = 11,
                            GenreName = "Sci-Fi",
                            Language = "English",
                            PhotoURL = "SpidermanHomecoming.jpg",
                            Price = 15.0,
                            ProducerID = 1,
                            ProducerName = "Kevin Feige",
                            Rating = 5.0,
                            ReleaseDate = new DateTime(2019, 7, 20, 21, 30, 15, 0, DateTimeKind.Unspecified),
                            Shipping = "Yes",
                            SoldItems = 43,
                            Title = "Spider-Man: Homecoming",
                            UserId = 0
                        },
                        new
                        {
                            Id = 17,
                            ActorNames = "Benedict Cumberbatch",
                            Country = "USA",
                            DateAdded = new DateTime(2021, 4, 17, 19, 28, 2, 691, DateTimeKind.Local).AddTicks(5492),
                            Description = "",
                            DirectorID = 15,
                            DirectorName = "Scott Derrickson",
                            Duration = "",
                            FormatType = "",
                            GenreID = 11,
                            GenreName = "Sci-Fi",
                            Language = "English",
                            PhotoURL = "DrStrange.jpg",
                            Price = 16.0,
                            ProducerID = 1,
                            ProducerName = "Kevin Feige",
                            Rating = 4.2999999999999998,
                            ReleaseDate = new DateTime(2019, 6, 20, 21, 30, 15, 0, DateTimeKind.Unspecified),
                            Shipping = "Yes",
                            SoldItems = 34,
                            Title = "Doctor Strange",
                            UserId = 0
                        },
                        new
                        {
                            Id = 18,
                            ActorNames = "Chadwick Boseman, Michael B. Jordan",
                            Country = "USA",
                            DateAdded = new DateTime(2021, 4, 17, 19, 28, 2, 691, DateTimeKind.Local).AddTicks(5497),
                            Description = "",
                            DirectorID = 16,
                            DirectorName = "Ryan Coogler",
                            Duration = "",
                            FormatType = "",
                            GenreID = 11,
                            GenreName = "Sci-Fi",
                            Language = "English",
                            PhotoURL = "BlackPanther.jpg",
                            Price = 16.0,
                            ProducerID = 1,
                            ProducerName = "Kevin Feige",
                            Rating = 4.4000000000000004,
                            ReleaseDate = new DateTime(2019, 4, 20, 21, 30, 15, 0, DateTimeKind.Unspecified),
                            Shipping = "Yes",
                            SoldItems = 32,
                            Title = "Black Panther",
                            UserId = 0
                        },
                        new
                        {
                            Id = 19,
                            ActorNames = "Chris Hemsworth, Idris Elba, Anthony Hopkins, Ray Stevenson, Tadanobu Asano,Tom Hiddleston",
                            Country = "USA",
                            DateAdded = new DateTime(2021, 4, 17, 19, 28, 2, 691, DateTimeKind.Local).AddTicks(5502),
                            Description = "",
                            DirectorID = 8,
                            DirectorName = "Taika Waititi",
                            Duration = "",
                            FormatType = "",
                            GenreID = 11,
                            GenreName = "Sci-Fi",
                            Language = "English",
                            PhotoURL = "ThorRagnarok.jpg",
                            Price = 17.0,
                            ProducerID = 1,
                            ProducerName = "Kevin Feige",
                            Rating = 5.0,
                            ReleaseDate = new DateTime(2019, 4, 23, 21, 30, 15, 0, DateTimeKind.Unspecified),
                            Shipping = "Yes",
                            SoldItems = 30,
                            Title = "Thor: Ragnarok",
                            UserId = 0
                        },
                        new
                        {
                            Id = 20,
                            ActorNames = "Chris Hemsworth, Mark Ruffalo, Scarlet Johannson, Karen Gillan, Robert Downey Jr., Samuel L. Jackson, Jeremy Lee Renner, Tom Hiddleston, Chris Evans, Brie Larson, Josh Brolin, Chadwick Boseman, Elizabeth Olsen, Chris Pratt, Zoe Saldana, Benedict Cumberbatch, Paul Bettany, Anthony Mackie, Sebastian Bach, Vin Diesel, Tom Holland",
                            Country = "USA",
                            DateAdded = new DateTime(2021, 4, 17, 19, 28, 2, 691, DateTimeKind.Local).AddTicks(5508),
                            Description = "",
                            DirectorID = 3,
                            DirectorName = "Anthony Russo",
                            Duration = "",
                            FormatType = "",
                            GenreID = 11,
                            GenreName = "Sci-Fi",
                            Language = "English",
                            PhotoURL = "AvengersInfinityWar.jpg",
                            Price = 22.0,
                            ProducerID = 1,
                            ProducerName = "Kevin Feige",
                            Rating = 5.0,
                            ReleaseDate = new DateTime(2020, 5, 20, 21, 30, 15, 0, DateTimeKind.Unspecified),
                            Shipping = "Yes",
                            SoldItems = 80,
                            Title = "Avengers: Infinity War",
                            UserId = 0
                        },
                        new
                        {
                            Id = 21,
                            ActorNames = "Paul Rudd, Evangeline Lilly, Michael Douglas",
                            Country = "USA",
                            DateAdded = new DateTime(2021, 4, 17, 19, 28, 2, 691, DateTimeKind.Local).AddTicks(5515),
                            Description = "",
                            DirectorID = 13,
                            DirectorName = "Peyton Reed",
                            Duration = "",
                            FormatType = "",
                            GenreID = 11,
                            GenreName = "Sci-Fi",
                            Language = "English",
                            PhotoURL = "AntManAndTheWasp.jpg",
                            Price = 14.0,
                            ProducerID = 1,
                            ProducerName = "Kevin Feige",
                            Rating = 4.5,
                            ReleaseDate = new DateTime(2020, 6, 20, 21, 30, 15, 0, DateTimeKind.Unspecified),
                            Shipping = "Yes",
                            SoldItems = 20,
                            Title = "Ant-Man and The Wasp",
                            UserId = 0
                        },
                        new
                        {
                            Id = 22,
                            ActorNames = "Chris Hemsworth, Mark Ruffalo, Scarlet Johannson, Karen Gillan, Robert Downey Jr., Samuel L. Jackson, Jeremy Lee Renner, Tom Hiddleston, Chris Evans, Brie Larson, Josh Brolin, Chadwick Boseman, Elizabeth Olsen, Chris Pratt, Zoe Saldana, Benedict Cumberbatch, Paul Bettany, Anthony Mackie, Sebastian Bach, Vin Diesel, Tom Holland",
                            Country = "USA",
                            DateAdded = new DateTime(2021, 4, 17, 19, 28, 2, 691, DateTimeKind.Local).AddTicks(5520),
                            Description = "",
                            DirectorID = 3,
                            DirectorName = "Anthony Russo",
                            Duration = "",
                            FormatType = "",
                            GenreID = 11,
                            GenreName = "Sci-Fi",
                            Language = "English",
                            PhotoURL = "AvengersEndGame.jpg",
                            Price = 20.0,
                            ProducerID = 1,
                            ProducerName = "Kevin Feige",
                            Rating = 5.0,
                            ReleaseDate = new DateTime(2020, 6, 15, 21, 30, 15, 0, DateTimeKind.Unspecified),
                            Shipping = "Yes",
                            SoldItems = 23,
                            Title = "Avengers: Endgame",
                            UserId = 0
                        },
                        new
                        {
                            Id = 23,
                            ActorNames = "Tom Holland, Jon Favreau, Zendaya, Samuel L. Jackson, Cobie Smulders, Jake Gyllenhaal",
                            Country = "USA",
                            DateAdded = new DateTime(2021, 4, 17, 19, 28, 2, 691, DateTimeKind.Local).AddTicks(5526),
                            Description = "",
                            DirectorID = 14,
                            DirectorName = "Jon Watts",
                            Duration = "",
                            FormatType = "",
                            GenreID = 11,
                            GenreName = "Sci-Fi",
                            Language = "English",
                            PhotoURL = "SpidermanFarFromHome.jpg",
                            Price = 12.0,
                            ProducerID = 1,
                            ProducerName = "Kevin Feige",
                            Rating = 5.0,
                            ReleaseDate = new DateTime(2020, 7, 20, 21, 30, 15, 0, DateTimeKind.Unspecified),
                            Shipping = "Yes",
                            SoldItems = 10,
                            Title = "Spider-Man: Far From Home",
                            UserId = 0
                        });
                });

            modelBuilder.Entity("Moviesite.Entities.MovieActor", b =>
                {
                    b.Property<int>("MovieID")
                        .HasColumnType("int");

                    b.Property<int>("ActorID")
                        .HasColumnType("int");

                    b.HasKey("MovieID", "ActorID");

                    b.HasIndex("ActorID");

                    b.ToTable("MovieActors");
                });

            modelBuilder.Entity("Moviesite.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MovieCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MovieCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MovieFormatType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MovieProducer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MovieTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("ShippedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Moviesite.Entities.Producer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime>("DateBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.ToTable("Producers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "USA",
                            DateBirth = new DateTime(2021, 4, 17, 19, 28, 2, 689, DateTimeKind.Local).AddTicks(3156),
                            Gender = "Male",
                            Name = "Kevin Feige",
                            ShortDescription = ""
                        });
                });

            modelBuilder.Entity("Moviesite.Entities.ShoppingCart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<double>("Discount")
                        .HasColumnType("float");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ShoppingCarts");
                });

            modelBuilder.Entity("Moviesite.Entities.Wishlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Wishlists");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Moviesite.Entities.Movie", b =>
                {
                    b.HasOne("Moviesite.Entities.Director", "Director")
                        .WithMany("Movies")
                        .HasForeignKey("DirectorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Moviesite.Entities.Genre", "Genre")
                        .WithMany("Movies")
                        .HasForeignKey("GenreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Moviesite.Entities.Producer", "Producer")
                        .WithMany("Movies")
                        .HasForeignKey("ProducerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Moviesite.Entities.MovieActor", b =>
                {
                    b.HasOne("Moviesite.Entities.Actor", "Actor")
                        .WithMany("MovieActors")
                        .HasForeignKey("ActorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Moviesite.Entities.Movie", "Movie")
                        .WithMany("MovieActors")
                        .HasForeignKey("MovieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
